CREATE TABLE FRAMEWORK (
	FRAMEWORKID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(200),
	AUTHOR VARCHAR(50),
	INFO LONG VARCHAR,
	VERSION VARCHAR(10),
	PRIMARY KEY (FRAMEWORKID)
);

CREATE TABLE FRAMEWORKITEM (
	FRAMEWORKID INTEGER NOT NULL,
	FRAMEWORKITEMID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPTION VARCHAR(200),
	STATUS BOOLEAN,
	PARENTFRAMEWORKID INTEGER,
	PARENTFRAMEWORKITEMID INTEGER,
	PRIMARY KEY (FRAMEWORKID,FRAMEWORKITEMID)
);

CREATE TABLE ICONS (
	ICONID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PATH VARCHAR(255),
	PRIMARY KEY (ICONID)
);

CREATE TABLE PROJECT (
	PROJECTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(80),
	CUSTOMER VARCHAR(50),
	STARTDATE DATE,
	ENDDATE DATE,
	AUTHOR VARCHAR(50),
	WORKDIR VARCHAR(255),
	FRAMEWORKID INTEGER,
	VERSION VARCHAR(10),
	PRIMARY KEY (PROJECTID)
);

CREATE TABLE PROJECTTOOL (
	PROJECTID INTEGER NOT NULL,
	TOOLID INTEGER NOT NULL,
	PRIMARY KEY (PROJECTID,TOOLID)
);

CREATE TABLE RISK (
	RISKID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(15),
	ICONID INTEGER,
	PRIMARY KEY (RISKID)
);

CREATE TABLE TARGET (
	PROJECTID INTEGER NOT NULL,
	TARGETID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(50),
	TARGETTYPEID INTEGER,
	PRIMARY KEY (PROJECTID,TARGETID)
);

CREATE TABLE TARGETITEM (
	PROJECTID INTEGER NOT NULL,
	TARGETID INTEGER NOT NULL,
	TARGETITEMID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	RISKID INTEGER,
	PORT INTEGER,
	PROTOCOL VARCHAR(10),
	NAME VARCHAR(50),
	CONTENT LONG VARCHAR,
	PRIMARY KEY (PROJECTID,TARGETID,TARGETITEMID)
);

CREATE TABLE TARGETTYPE (
	TARGETTYPEID INTEGER NOT NULL,
	NAME VARCHAR(50),
	VERSION VARCHAR(50),
	ICONID INTEGER,
	PRIMARY KEY (TARGETTYPEID)
);

CREATE TABLE TOOL (
	TOOLID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(50),
	VERSION VARCHAR(10),
	AUTHOR VARCHAR(50),
	INFO LONG VARCHAR,
	COMMAND LONG VARCHAR,
	WORKDIR VARCHAR(255),
	ENABLED BOOLEAN,
	PRIMARY KEY (TOOLID)
);

ALTER TABLE FRAMEWORKITEM
	ADD FOREIGN KEY (FRAMEWORKID) 
	REFERENCES FRAMEWORK (FRAMEWORKID);



ALTER TABLE PROJECT
	ADD FOREIGN KEY (FRAMEWORKID) 
	REFERENCES FRAMEWORK (FRAMEWORKID);



ALTER TABLE PROJECTTOOL
	ADD FOREIGN KEY (PROJECTID) 
	REFERENCES PROJECT (PROJECTID);

ALTER TABLE PROJECTTOOL
	ADD FOREIGN KEY (TOOLID) 
	REFERENCES TOOL (TOOLID);



ALTER TABLE RISK
	ADD FOREIGN KEY (ICONID) 
	REFERENCES ICONS (ICONID);



ALTER TABLE TARGET
	ADD FOREIGN KEY (PROJECTID) 
	REFERENCES PROJECT (PROJECTID);

ALTER TABLE TARGET
	ADD FOREIGN KEY (TARGETTYPEID) 
	REFERENCES TARGETTYPE (TARGETTYPEID);



ALTER TABLE TARGETITEM
	ADD FOREIGN KEY (RISKID) 
	REFERENCES RISK (RISKID);

ALTER TABLE TARGETITEM
	ADD FOREIGN KEY (PROJECTID,TARGETID) 
	REFERENCES TARGET (PROJECTID,TARGETID);



ALTER TABLE TARGETTYPE
	ADD FOREIGN KEY (ICONID) 
	REFERENCES ICONS (ICONID);



