INSERT INTO ICONS (PATH) VALUES ('none');
INSERT INTO ICONS (PATH) VALUES ('critical');
INSERT INTO ICONS (PATH) VALUES ('high');
INSERT INTO ICONS (PATH) VALUES ('medium');
INSERT INTO ICONS (PATH) VALUES ('low');
INSERT INTO ICONS (PATH) VALUES ('info');
INSERT INTO ICONS (PATH) VALUES ('tbc');

INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (1, 'None', 1);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (2, 'Critical', 2);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (3, 'High', 3);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (4, 'Medium', 4);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (5, 'Low', 5);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (6, 'Info', 6);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (7, 'TBC', 7);


INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (1, 'webapp', '1');
INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (2, 'server', '1');
INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (3, 'mail', '1');