INSERT INTO ICONS (PATH) VALUES ('none');
INSERT INTO ICONS (PATH) VALUES ('risk/critical');
INSERT INTO ICONS (PATH) VALUES ('risk/high');
INSERT INTO ICONS (PATH) VALUES ('risk/medium');
INSERT INTO ICONS (PATH) VALUES ('risk/low');
INSERT INTO ICONS (PATH) VALUES ('risk/info');
INSERT INTO ICONS (PATH) VALUES ('risk/tbc');

INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (1, 'None', 1);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (2, 'Critical', 2);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (3, 'High', 3);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (4, 'Medium', 4);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (5, 'Low', 5);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (6, 'Info', 6);
INSERT INTO RISK (RISKID, DESCRIPTION, ICONID) VALUES (7, 'TBC', 7);


INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (1, 'host', '1');
INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (2, 'webapp', '1');
INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (3, 'range', '1');
INSERT INTO TARGETTYPE (TARGETTYPEID, NAME, VERSION) VALUES (4, 'network', '1');